enum ActionTypes {
	CHANGE_NICKNAME = "CHANGE_NICKNAME",
	CHANGE_ENEMY_NICKNAME = "CHANGE_ENEMY_NICKNAME",
    CHANGE_PLAYER_COLOR = "CHANGE_PLAYER_COLOR"
};

export const {
    CHANGE_NICKNAME,
    CHANGE_ENEMY_NICKNAME,
    CHANGE_PLAYER_COLOR
} = ActionTypes;
