enum ActionTypes {
  CHANGE_NICKNAME = "CHANGE_NICKNAME",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",
  CHANGE_EMAIL = "CHANGE_EMAIL",
  CHANGE_OPERATION = "CHANGE_OPERATION",
}

export const {
  CHANGE_NICKNAME,
  CHANGE_PASSWORD,
  CHANGE_EMAIL,
  CHANGE_OPERATION,
} = ActionTypes;
