enum GameActionTypes {
	SEND_INVITE = "SEND_INVITE",
	ACCEPT_INVITE = "ACCEPT_INVITE",
	CREATE_GAME = "CREATE_GAME",
	JOIN_GAME = "JOIN_GAME",
}

export const { SEND_INVITE, ACCEPT_INVITE, CREATE_GAME, JOIN_GAME } =
	GameActionTypes;
